name: fractal_stranger
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  image: any
  flutter_svg: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: any

flutter:
  uses-material-design: true
  assets:
  - assets/sstu_logo.svg
  fonts:
  - family: Jost
    fonts:
    - asset: assets\Jost-VariableFont_wght.ttf